Repository WanF-Project/WanF-Project-Server, pull requests merged in 2023-07, with the labels that each got.

#74 User test code 작성
  src/main/java/com/capstone/wanf/auth/jwt/service/AuthService.java
  src/main/java/com/capstone/wanf/user/controller/EmailController.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/domain/entity/User.java
  src/main/java/com/capstone/wanf/user/domain/repo/UserRepository.java
  src/main/java/com/capstone/wanf/user/dto/request/CodeRequest.java
  src/main/java/com/capstone/wanf/user/dto/request/EmailRequest.java
  src/main/java/com/capstone/wanf/user/dto/request/UserRequest.java
  src/main/java/com/capstone/wanf/user/dto/response/UserResponse.java
  src/main/java/com/capstone/wanf/user/service/EmailService.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/user/domain/repo/UserRepositoryTest.java
  src/test/java/com/capstone/wanf/user/service/EmailServiceTest.java
  src/test/java/com/capstone/wanf/user/service/UserServiceTest.java
Labels: feat, Refactoring, test

#78 Pagination Post DTO 추가
  src/main/java/com/capstone/wanf/course/domain/entity/Course.java
  src/main/java/com/capstone/wanf/course/dto/response/CoursePaginationResponse.java
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/post/domain/entity/Post.java
  src/main/java/com/capstone/wanf/post/domain/repo/PostRepositorySupport.java
  src/main/java/com/capstone/wanf/post/dto/response/PostPaginationResponse.java
  src/main/java/com/capstone/wanf/post/service/PostService.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
  src/test/java/com/capstone/wanf/post/service/PostServiceTest.java
  src/test/java/com/capstone/wanf/profile/domain/repo/ProfileRepositoryTest.java
Labels: feat, Refactoring

#79 feat: 강의 검색 기능 추가
  src/main/java/com/capstone/wanf/comment/dto/response/CommentResponse.java
  src/main/java/com/capstone/wanf/course/controller/CourseController.java
  src/main/java/com/capstone/wanf/course/domain/repo/CourseRepositorySupport.java
  src/main/java/com/capstone/wanf/course/dto/request/CourseRequest.java
  src/main/java/com/capstone/wanf/course/dto/response/CoursePaginationResponse.java
  src/main/java/com/capstone/wanf/course/service/CourseService.java
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/post/domain/entity/Category.java
  src/main/java/com/capstone/wanf/post/domain/repo/PostRepositorySupport.java
  src/main/java/com/capstone/wanf/post/dto/request/PostRequest.java
  src/main/java/com/capstone/wanf/post/dto/response/PostPaginationResponse.java
  src/main/java/com/capstone/wanf/post/dto/response/PostResponse.java
  src/main/java/com/capstone/wanf/post/service/PostService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/comment/controller/CommentControllerTest.java
  src/test/java/com/capstone/wanf/config/TestQueryDslConfig.java
  src/test/java/com/capstone/wanf/course/controller/CourseControllerTest.java
  src/test/java/com/capstone/wanf/course/domain/entity/CourseTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/CourseRepositoryTest.java
  src/test/java/com/capstone/wanf/course/service/CourseServiceTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/post/controller/PostControllerTest.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
  src/test/java/com/capstone/wanf/post/service/PostServiceTest.java
Labels: feat, Refactoring

#82 게시글 검색 조건 변경
  src/main/java/com/capstone/wanf/post/domain/entity/Post.java
  src/main/java/com/capstone/wanf/post/domain/repo/PostRepositorySupport.java
  src/test/java/com/capstone/wanf/post/controller/PostControllerTest.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
Labels: test, fix

#85 회원가입 로직 수정
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
Labels: feat
