Repository WanF-Project/WanF-Project-Server, pull requests merged in 2023-05, with the labels that each got.

#40 profile API
  src/main/java/com/capstone/wanf/common/annotation/ExeTimer.java
  src/main/java/com/capstone/wanf/common/aop/ExecutionTimer.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
Labels: feat

#41 페이징 없는 게시물 모두 조회
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/post/domain/repo/PostRepositorySupport.java
  src/main/java/com/capstone/wanf/post/service/PostService.java
Labels: feat

#42 전공 모두 조회
  src/main/java/com/capstone/wanf/major/controller/MajorController.java
  src/main/java/com/capstone/wanf/major/service/MajorService.java
Labels: feat

#43 swagger https 적용
  src/main/java/com/capstone/wanf/config/OpenApiConfig.java
Labels: documentation

#44 Profile update 메소드 수정
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileRequest.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
Labels: bug

#47 디렉토리 구조 변경
  src/main/java/com/capstone/wanf/auth/jwt/domain/UserDetailsImpl.java
  src/main/java/com/capstone/wanf/auth/jwt/dto/response/TokenResponse.java
  src/main/java/com/capstone/wanf/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/capstone/wanf/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/capstone/wanf/auth/jwt/service/AuthService.java
  src/main/java/com/capstone/wanf/auth/jwt/service/UserDetailsServiceImpl.java
  src/main/java/com/capstone/wanf/auth/redis/config/RedisRepositoryConfig.java
  src/main/java/com/capstone/wanf/auth/redis/service/RedisService.java
  src/main/java/com/capstone/wanf/comment/controller/CommentController.java
  src/main/java/com/capstone/wanf/config/SecurityConfig.java
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
Labels: Refactoring

#48 로그인 api error 상태코드 수정
  src/main/java/com/capstone/wanf/auth/jwt/service/UserDetailsServiceImpl.java
  src/main/java/com/capstone/wanf/config/SecurityConfig.java
  src/main/java/com/capstone/wanf/error/handler/GlobalExceptionHandler.java
Labels: feat

#50 Course test code
  build.gradle
  lombok.config
  src/main/java/com/capstone/wanf/course/controller/MajorController.java
  src/main/java/com/capstone/wanf/course/domain/entity/Course.java
  src/main/java/com/capstone/wanf/course/domain/entity/Major.java
  src/main/java/com/capstone/wanf/course/domain/repo/MajorRepository.java
  src/main/java/com/capstone/wanf/course/service/MajorService.java
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/main/resources/application.yml
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/SupportRestAssured.java
  src/test/java/com/capstone/wanf/course/controller/CourseControllerTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/CourseRepositoryTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/MajorRepositoryTest.java
  src/test/java/com/capstone/wanf/course/service/CourseServiceTest.java
  src/test/java/com/capstone/wanf/course/service/MajorServiceTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/resources/application.yml
Labels: test

#55 프로필 api 수정
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
Labels: feat

#52 Course, Major test code 추가
  src/main/java/com/capstone/wanf/course/controller/CourseController.java
  src/main/java/com/capstone/wanf/course/controller/MajorController.java
  src/main/java/com/capstone/wanf/course/service/CourseService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/SupportRestAssured.java
  src/test/java/com/capstone/wanf/course/controller/CourseControllerTest.java
  src/test/java/com/capstone/wanf/course/controller/MajorControllerTest.java
  src/test/java/com/capstone/wanf/course/domain/entity/CourseTest.java
  src/test/java/com/capstone/wanf/course/domain/entity/MajorTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/CourseRepositoryTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/profile/domain/repo/ProfileRepositoryTest.java
  src/test/resources/truncate.sql
Labels: test

#59 ADMIN Role을 가진 사용자만 접근 가능한 API 작성 featNew feature or request
  src/main/java/com/capstone/wanf/auth/jwt/domain/UserDetailsImpl.java
  src/main/java/com/capstone/wanf/config/SecurityConfig.java
  src/main/java/com/capstone/wanf/course/controller/CourseController.java
  src/main/java/com/capstone/wanf/course/controller/MajorController.java
  src/main/java/com/capstone/wanf/course/dto/request/RequestCourse.java
  src/main/java/com/capstone/wanf/course/dto/request/RequestMajor.java
  src/main/java/com/capstone/wanf/course/service/CourseService.java
  src/main/java/com/capstone/wanf/course/service/MajorService.java
  src/main/java/com/capstone/wanf/error/handler/GlobalExceptionHandler.java
  src/main/java/com/capstone/wanf/error/handler/JwtAccessDeniedHandler.java
  src/main/java/com/capstone/wanf/error/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/domain/entity/User.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/course/controller/CourseControllerTest.java
  src/test/java/com/capstone/wanf/course/controller/MajorControllerTest.java
  src/test/java/com/capstone/wanf/course/service/CourseServiceTest.java
  src/test/java/com/capstone/wanf/course/service/MajorServiceTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/resources/truncate.sql
Labels: feat
