Repository WanF-Project/WanF-Project-Server, pull requests merged in 2023-08, with the labels that each got.

#86 프로필 로직 수정
  src/main/java/com/capstone/wanf/error/errorcode/CommonErrorCode.java
  src/main/java/com/capstone/wanf/error/handler/GlobalExceptionHandler.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileRequest.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/course/controller/MajorControllerTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/CourseRepositoryTest.java
  src/test/java/com/capstone/wanf/course/domain/repo/MajorRepositoryTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/resources/truncate.sql
Labels: feat

#89 모임 api
  src/main/java/com/capstone/wanf/club/controller/ClubController.java
  src/main/java/com/capstone/wanf/club/controller/ClubPostController.java
  src/main/java/com/capstone/wanf/club/domain/entity/Authority.java
  src/main/java/com/capstone/wanf/club/domain/entity/Club.java
  src/main/java/com/capstone/wanf/club/domain/entity/ClubAuth.java
  src/main/java/com/capstone/wanf/club/domain/entity/ClubPost.java
  src/main/java/com/capstone/wanf/club/domain/repo/ClubAuthRepository.java
  src/main/java/com/capstone/wanf/club/domain/repo/ClubRepository.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubPostRequest.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubPwdRequest.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubRequest.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubDetailResponse.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubPostResponse.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubResponse.java
  src/main/java/com/capstone/wanf/club/service/ClubAuthService.java
  src/main/java/com/capstone/wanf/club/service/ClubPostService.java
  src/main/java/com/capstone/wanf/club/service/ClubService.java
  src/main/java/com/capstone/wanf/error/errorcode/CustomErrorCode.java
Labels: feat

#91 이미지 업로드
  build.gradle
  src/main/java/com/capstone/wanf/club/controller/ClubController.java
  src/main/java/com/capstone/wanf/club/controller/ClubPostController.java
  src/main/java/com/capstone/wanf/club/domain/entity/Club.java
  src/main/java/com/capstone/wanf/club/domain/entity/ClubPost.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubPostRequest.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubPwdRequest.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubRequest.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubPostResponse.java
  src/main/java/com/capstone/wanf/club/service/ClubPostService.java
  src/main/java/com/capstone/wanf/comment/domain/entity/Comment.java
  src/main/java/com/capstone/wanf/config/AwsS3Config.java
  src/main/java/com/capstone/wanf/error/errorcode/CommonErrorCode.java
  src/main/java/com/capstone/wanf/error/errorcode/CustomErrorCode.java
  src/main/java/com/capstone/wanf/error/handler/GlobalExceptionHandler.java
  src/main/java/com/capstone/wanf/message/service/ConsumerService.java
  src/main/java/com/capstone/wanf/post/domain/entity/Post.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/domain/entity/ProfileImage.java
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileImageRequest.java
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileRequest.java
  src/main/java/com/capstone/wanf/profile/dto/response/ProfileResponse.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/main/java/com/capstone/wanf/storage/controller/ImageController.java
  src/main/java/com/capstone/wanf/storage/domain/entity/Directory.java
  src/main/java/com/capstone/wanf/storage/domain/entity/Image.java
  src/main/java/com/capstone/wanf/storage/domain/repo/ImageRepository.java
  src/main/java/com/capstone/wanf/storage/dto/response/ImageResponse.java
  src/main/java/com/capstone/wanf/storage/service/S3Service.java
  src/main/resources/application.yml
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
  src/test/java/com/capstone/wanf/profile/controller/ProfileControllerTest.java
  src/test/java/com/capstone/wanf/profile/domain/entity/ProfileTest.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
  src/test/resources/application.yml
  src/test/resources/truncate.sql
Labels: feat, test

#93 쪽지 조회 반환 데이터 구조 변경
  src/main/java/com/capstone/wanf/error/errorcode/CommonErrorCode.java
  src/main/java/com/capstone/wanf/message/controller/ProduceController.java
  src/main/java/com/capstone/wanf/message/converter/MessageConverter.java
  src/main/java/com/capstone/wanf/message/domain/entity/Message.java
  src/main/java/com/capstone/wanf/message/domain/repo/MessageRepository.java
  src/main/java/com/capstone/wanf/message/domain/repo/MessageRepositorySupport.java
  src/main/java/com/capstone/wanf/message/dto/response/MessageResponse.java
  src/main/java/com/capstone/wanf/message/dto/response/ReceiverMessageResponse.java
  src/main/java/com/capstone/wanf/message/service/ConsumerService.java
  src/main/java/com/capstone/wanf/message/service/ProducerService.java
Labels: feat, fix

#95 Profile contact 필드 삭제
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileRequest.java
  src/main/java/com/capstone/wanf/profile/dto/response/ProfileResponse.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
  src/test/java/com/capstone/wanf/profile/domain/entity/ProfileTest.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
Labels: test, fix

#97 랜덤 친구 추천 기능 구현
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/domain/repo/ProfileRepositorySupport.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
Labels: feat

#99 프로필 필드(목표, 성격) 보기 추가
  src/main/java/com/capstone/wanf/profile/domain/entity/Goal.java
  src/main/java/com/capstone/wanf/profile/domain/entity/Personality.java
Labels: feat

#100 쪽지 기능 테스트
  src/main/java/com/capstone/wanf/message/controller/MessageConsumerController.java
  src/main/java/com/capstone/wanf/message/controller/MessageProduceController.java
  src/main/java/com/capstone/wanf/message/service/MessageConsumerService.java
  src/main/java/com/capstone/wanf/message/service/MessageProducerService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/message/controller/MessageControllerTest.java
  src/test/java/com/capstone/wanf/message/converter/MessageConverterTest.java
  src/test/java/com/capstone/wanf/message/service/MessageServiceTest.java
  src/test/resources/truncate.sql
Labels: Refactoring, test

#103 기본 프로필 이미지 삭제
  src/main/java/com/capstone/wanf/profile/dto/request/ProfileImageRequest.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
Labels: feat, test
