Repository WanF-Project/WanF-Project-Server, pull requests merged in 2023-09, with the labels that each got.

#109 Firebase 다중 기기 등록
  src/main/java/com/capstone/wanf/comment/service/CommentService.java
  src/main/java/com/capstone/wanf/firebase/service/FCMService.java
  src/main/java/com/capstone/wanf/message/service/MessageConsumerService.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/domain/entity/User.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
Labels: feat, Refactoring

#111 Firebase 추가로 인한 테스트 수정 및 FCM 로직 테스트 코드 추가
  build.gradle
  src/main/java/com/capstone/wanf/config/FirebaseConfig.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/comment/controller/CommentControllerTest.java
  src/test/java/com/capstone/wanf/comment/service/CommentServiceTest.java
  src/test/java/com/capstone/wanf/firebase/service/FCMServiceTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/message/controller/MessageControllerTest.java
  src/test/java/com/capstone/wanf/message/service/MessageServiceTest.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
Labels: test, fix

#113 User 테스트 코드 작성
  build.gradle
  src/main/java/com/capstone/wanf/auth/jwt/service/AuthService.java
  src/main/java/com/capstone/wanf/user/controller/EmailController.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/domain/entity/User.java
  src/main/java/com/capstone/wanf/user/service/UserService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/SupportRestAssured.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/user/controller/UserControllerTest.java
  src/test/java/com/capstone/wanf/user/domain/entity/UserTest.java
  src/test/java/com/capstone/wanf/user/domain/repo/UserRepositoryTest.java
  src/test/java/com/capstone/wanf/user/service/UserServiceTest.java
  src/test/resources/truncate.sql
Labels: refactor, test

#116 auth 로직 리펙토링 및 주석 수정
  src/main/java/com/capstone/wanf/auth/jwt/domain/UserDetailsImpl.java
  src/main/java/com/capstone/wanf/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/capstone/wanf/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/capstone/wanf/auth/jwt/service/AuthService.java
  src/main/java/com/capstone/wanf/auth/jwt/service/UserDetailsServiceImpl.java
  src/main/java/com/capstone/wanf/auth/redis/config/RedisRepositoryConfig.java
  src/main/java/com/capstone/wanf/auth/redis/service/RedisService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/post/domain/repo/PostRepositoryTest.java
Labels: docs, refactor, test

#117 로그인 응답 데이터 변경
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/dto/response/LoginResponse.java
Labels: fix

#118 API 문서(swagger) 간소화
  src/main/java/com/capstone/wanf/club/controller/ClubController.java
  src/main/java/com/capstone/wanf/club/controller/ClubPostController.java
  src/main/java/com/capstone/wanf/club/domain/entity/Club.java
  src/main/java/com/capstone/wanf/club/service/ClubAuthService.java
  src/main/java/com/capstone/wanf/club/service/ClubPostService.java
  src/main/java/com/capstone/wanf/club/service/ClubService.java
  src/main/java/com/capstone/wanf/comment/controller/CommentController.java
  src/main/java/com/capstone/wanf/course/controller/CourseController.java
  src/main/java/com/capstone/wanf/course/controller/MajorController.java
  src/main/java/com/capstone/wanf/error/errorcode/CommonErrorCode.java
  src/main/java/com/capstone/wanf/message/controller/MessageConsumerController.java
  src/main/java/com/capstone/wanf/message/controller/MessageProduceController.java
  src/main/java/com/capstone/wanf/message/service/MessageProducerService.java
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/storage/controller/ImageController.java
  src/main/java/com/capstone/wanf/user/controller/EmailController.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
Labels: docs, refactor, fix

#120 모임, 모임 게시글 test code 추가 및 리펙토링 진행
  build.gradle
  src/main/java/com/capstone/wanf/club/controller/ClubController.java
  src/main/java/com/capstone/wanf/club/controller/ClubPostController.java
  src/main/java/com/capstone/wanf/club/domain/entity/Club.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubPostRequest.java
  src/main/java/com/capstone/wanf/club/dto/request/ClubRequest.java
  src/main/java/com/capstone/wanf/club/service/ClubAuthService.java
  src/main/java/com/capstone/wanf/club/service/ClubPostService.java
  src/main/java/com/capstone/wanf/club/service/ClubService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/club/controller/ClubControllerTest.java
  src/test/java/com/capstone/wanf/club/controller/ClubPostControllerTest.java
  src/test/java/com/capstone/wanf/club/domain/entity/ClubPostTest.java
  src/test/java/com/capstone/wanf/club/domain/entity/ClubTest.java
  src/test/java/com/capstone/wanf/club/service/ClubPostServiceTest.java
  src/test/java/com/capstone/wanf/club/service/ClubServiceAuthTest.java
  src/test/java/com/capstone/wanf/club/service/ClubServiceTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
Labels: refactor, test

#121 랜덤 친구 추천 로직 수정 & 테스트
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/domain/repo/ProfileRepositorySupport.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/test/java/com/capstone/wanf/ControllerTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/profile/controller/ProfileControllerTest.java
  src/test/java/com/capstone/wanf/profile/domain/repo/ProfileRepositoryTest.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
Labels: test, fix

#123 dto 변환 메소드를 domain -> dto(record)로 변경
  src/main/java/com/capstone/wanf/club/controller/ClubController.java
  src/main/java/com/capstone/wanf/club/controller/ClubPostController.java
  src/main/java/com/capstone/wanf/club/domain/entity/Club.java
  src/main/java/com/capstone/wanf/club/domain/entity/ClubPost.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubDetailResponse.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubPostResponse.java
  src/main/java/com/capstone/wanf/club/dto/response/ClubResponse.java
  src/main/java/com/capstone/wanf/club/service/ClubAuthService.java
  src/main/java/com/capstone/wanf/club/service/ClubPostService.java
  src/main/java/com/capstone/wanf/comment/controller/CommentController.java
  src/main/java/com/capstone/wanf/comment/domain/entity/Comment.java
  src/main/java/com/capstone/wanf/comment/dto/response/CommentResponse.java
  src/main/java/com/capstone/wanf/course/domain/entity/Course.java
  src/main/java/com/capstone/wanf/course/dto/response/CoursePaginationResponse.java
  src/main/java/com/capstone/wanf/message/converter/MessageConverter.java
  src/main/java/com/capstone/wanf/message/dto/response/MessageResponse.java
  src/main/java/com/capstone/wanf/message/dto/response/ReceiverMessageResponse.java
  src/main/java/com/capstone/wanf/message/service/MessageConsumerService.java
  src/main/java/com/capstone/wanf/post/controller/PostController.java
  src/main/java/com/capstone/wanf/post/domain/entity/Post.java
  src/main/java/com/capstone/wanf/post/domain/repo/PostRepositorySupport.java
  src/main/java/com/capstone/wanf/post/dto/response/PostPaginationResponse.java
  src/main/java/com/capstone/wanf/post/dto/response/PostResponse.java
  src/main/java/com/capstone/wanf/profile/controller/ProfileController.java
  src/main/java/com/capstone/wanf/profile/domain/entity/Profile.java
  src/main/java/com/capstone/wanf/profile/domain/repo/ProfileRepositorySupport.java
  src/main/java/com/capstone/wanf/profile/dto/response/MBTIResponse.java
  src/main/java/com/capstone/wanf/profile/dto/response/ProfileResponse.java
  src/main/java/com/capstone/wanf/profile/service/ProfileService.java
  src/main/java/com/capstone/wanf/storage/domain/entity/Image.java
  src/main/java/com/capstone/wanf/storage/dto/response/ImageResponse.java
  src/main/java/com/capstone/wanf/user/controller/UserController.java
  src/main/java/com/capstone/wanf/user/domain/entity/User.java
  src/main/java/com/capstone/wanf/user/dto/response/LoginResponse.java
  src/main/java/com/capstone/wanf/user/dto/response/UserResponse.java
  src/main/java/com/capstone/wanf/user/service/EmailService.java
  src/test/java/com/capstone/wanf/club/domain/entity/ClubPostTest.java
  src/test/java/com/capstone/wanf/club/domain/entity/ClubTest.java
  src/test/java/com/capstone/wanf/club/service/ClubPostServiceTest.java
  src/test/java/com/capstone/wanf/club/service/ClubServiceAuthTest.java
  src/test/java/com/capstone/wanf/comment/domain/entity/CommentTest.java
  src/test/java/com/capstone/wanf/fixture/DomainFixture.java
  src/test/java/com/capstone/wanf/message/service/MessageServiceTest.java
  src/test/java/com/capstone/wanf/post/domain/entity/PostTest.java
  src/test/java/com/capstone/wanf/profile/domain/entity/ProfileTest.java
  src/test/java/com/capstone/wanf/profile/service/ProfileServiceTest.java
  src/test/java/com/capstone/wanf/user/domain/entity/UserTest.java
Labels: refactor

#125 쪽지를 주고받은 사용자의 프로필 조회 로직 수정
  src/main/java/com/capstone/wanf/message/controller/MessageConsumerController.java
  src/main/java/com/capstone/wanf/message/domain/repo/MessageRepositorySupport.java
  src/main/java/com/capstone/wanf/message/dto/response/ReceiverMessageResponse.java
  src/main/java/com/capstone/wanf/message/service/MessageConsumerService.java
  src/test/java/com/capstone/wanf/message/service/MessageServiceTest.java
Labels: bug, fix

#127 주석, README 수정
  README.md
  src/main/java/com/capstone/wanf/config/AwsS3Config.java
  src/main/java/com/capstone/wanf/config/ScheduleConfig.java
  src/main/java/com/capstone/wanf/config/SecurityConfig.java
  src/main/java/com/capstone/wanf/config/UserBatchConfig.java
  src/main/java/com/capstone/wanf/storage/service/S3Service.java
Labels: docs
